server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create | create-drop | update | validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
# Custom JWT config
jwt:
  secret: my_super_secret_jwt_key_1234567890
  expiration: 36000000 # milliseconds (10h)

